version: 2.0.{build}
branches:
  only:
  - redesign-2020
  - deploy/*
image: Visual Studio 2017
environment:
  AutoParameterizationWebConfigConnectionStrings: false
  APPVEYOR_WAP_ARTIFACT_NAME: UAC
  APPVEYOR_WAP_SKIP_ACLS: true
  TSD_ARTIFACT_NAME: UAC
  TSD_DEPLOY_SITE: true
  TSD_SITE_NAME: umbracodemo1.ucommerce.net

test: off
  
nuget:
   account_feed: true
   
before_build:
- cmd: nuget restore src\AvenueClothing.sln
#- cmd: npm install -g gulp
#- cmd: appveyor-retry npm install
#- cmd: gulp build

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

build:
  project: src\AvenueClothing.sln
  publish_wap: true
  verbosity: minimal

for:
-
 branches:
  only:
   - redesign-2020
   - deploy/staging
 configuration: Debug
 deploy:
    - provider: Environment
      name: Amazon-UAT-WEB-01
